server:
  port: 7901                   #程序启动之后的端口 也就是tomcat的端口
spring:
  application:
    name: provider-user        #应用名称
eureka:
  instance:
    instance-id: provider7901  #注册进入eureka的服务的别名
    prefer-ip-address: true    #显示IP地址
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:10000/eureka