server:
  port: 8900
spring:
  application:
    name: consumer-order
user:
  url: http://localhost:7901/user/
eureka:
  instance:
    instance-id: provider8900  #注册进入eureka的服务的别名
    prefer-ip-address: true    #显示IP地址
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:10000/eureka
info:
  author: Pandy
  build-version: $project.version$