server:
  port: 10000
spring:
  application:
    name: eureka-server
  #security:
    #user:
      #name: user
      #password: 123
# 因为当前的eureka是单机的 所以需要做一些配置
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # false 表示eureka不会向注册中心注册自己
    fetch-registry: false       # false表示自己就是注册中心 只负责检索
    service-url:
      defaultZone: http://localhost:10000/eureka

